set(CMAKE_MODULE_PATH_OLD ${CMAKE_MODULE_PATH})
# TODO: Use list(FILTER ...) to remove CMAKE_CURRENT_LIST_DIR
set(CMAKE_MODULE_PATH "")
find_package(PNG)
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH_OLD})
unset(CMAKE_MODULE_PATH_OLD)

if (PNG_FOUND AND NOT WIN32)
  find_library(PNG_M_LIBRARY NAMES m)
  list(APPEND PNG_LIBRARIES "m")
  if(TARGET PNG::PNG)
    set_property(TARGET PNG::PNG APPEND PROPERTY INTERFACE_LINK_LIBRARIES "m")
  endif()
endif()
