foreach(flag_var IN ITEMS 
    CMAKE_C_FLAGS_INIT
    CMAKE_C_FLAGS_DEBUG_INIT
    CMAKE_C_FLAGS_MINSIZEREL_INIT
    CMAKE_C_FLAGS_RELEASE_INIT
    CMAKE_C_FLAGS_RELWITHDEBINFO_INIT
    CMAKE_CXX_FLAGS_INIT
    CMAKE_CXX_FLAGS_DEBUG_INIT
    CMAKE_CXX_FLAGS_MINSIZEREL_INIT
    CMAKE_CXX_FLAGS_RELEASE_INIT
    CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT)
        string(REGEX REPLACE "[/-]M[DT]d?" "/MT" ${flag_var} "${${flag_var}} /MT")
endforeach()
